### ISSUE TITLE
Issue with Package.xml Generator

### ISSUE THREAD

**Issue by meta-udit-singhal** [JJLongoria/aura-helper#38]
I have a query regarding the package.xml generator feature. Aura helper documentation suggests:- 
"Create package and destructive files quickly with the powerful Package Generator. Select metadata manually or _create the files from two git branches, commits or tags differences._".
Could anyone guide me on how can I create a Package.xml from the difference between the two branches?

Also, advanced GUI doesn't seem to work on windows. I have already enabled advanced GUI from aura helper settings but it is not working. Can someone guide me if I am missing something?

Thanks

**Comment by JJLongoria** [comment]
Hello, thanks for comment and use Aura Helper. I need to deactivate The advance graphic interface because use to many resources and not work in all computers, instead I develop the same systems and options with the VSCode Standard interface and options but is not fully available now. 

I will publish this weekend the new 3.0.0 version of Aura Helper and Aura Helper CLI (And Aura Helper Framework) to fix all existing errors and enhance Aura Helper performance. From this weeken you can use the Package Generator with all its options (like generate it from git). Its the best Aura Helper update with enhanced Intellisense and other features.

Sorry for the problems, I develop it alone on my free time and its a really huge extension (I develop an entire NodeJS Framework to powered the extension and client).  

I will to send you a message when publish the new version.

Best Regards.
Kanko

**Comment by JJLongoria** [comment]
Hi @meta-udit-singhal I published now the new v3.0.0 version. You can try to create packages from GIT (or other sources) and try the other enhanced or new features.

Thanks for contacts and enjoy Aura Helper!

Best Regards
Kanko
