### ISSUE TITLE
One Projection Clause Per Line - request

### ISSUE THREAD

**Issue by brylaen** [JJLongoria/aura-helper#44]
Hi,
awesome extension but I have one request if its possible about formatting SOQL.
Can we have setting  to format conditions to be one per line.

Before
`WHERE Name = '' OR Name = ''  AND Name = ''];`
After
```
WHERE Name = '' 
 OR Name = ''  
 AND Name = ''];
```
Something like this will be great.
Thanks alot

**Comment by brylaen** [comment]
And one more thing what I like if is posible.
To conditions to be formatted to new line
Before
if (acc.ParentId != oldAcc.ParentId && oldAcc.ParentId != Null)
After
if (acc.ParentId != oldAcc.ParentId 
&& oldAcc.ParentId != Null)

This would be also nice

**Comment by JJLongoria** [comment]
Hello @brylaen, thanks for the suggestions, I try to implement it on new releases, i notice you when publish this features.

Thanks for use Aura Helper, I hope you like it!

Regards!

**Comment by brylaen** [comment]
Thank you for looking on this

**Comment by brylaen** [comment]
Hi again I find one more thing that I would like to have. We already have

**Comment by JJLongoria** [comment]
Hello @brylaen sorry for the late response. I maintenance Aura Helper and all related software in my free time... and im too bussy in the last months, but i recently pubish a new version of Aura Helper, 4.5.0 with few enhancements.

I added new formatter configs like:
- **Add Whitespace Before Open Parenthesis Operator**: To add whitespace before (
- **Add Whitespace After Close Parenthesis Operator**: To add whitespace after )
- **SObject Fields Per Line**: To select the fields per line on Sobject declaration (similar to Max fields on query projection) as: 
```
Case cs = new Case(field1 = value, field2 = value, field3 = value) 
to
Case cs = new Case(
    field1 = value,
    field2 = value,
    field3 = value
)
```
- **Max Conditions Per Line**: To select the first level conditions on control flow statements like:
```
if (acc.ParentId != oldAcc.ParentId && oldAcc.ParentId != Null)
After
if (acc.ParentId != oldAcc.ParentId
&& oldAcc.ParentId != Null)
```
- **Condition Logic Operator On New Line**: Option to add the && or || simbol on condition on new line when Max Conditions Per Line is active

Also fix minor errors and add support to Aura Helper SF Plugin.

Aura Helper SF Plugin is the Aura Helper SFDX Plugin evolution because it is the same tool, but adapted to the new SF CLI and add support to Aura Helper to detect and handle command from Aura Helper SF or Aura Helper SFDX and the old and new SF or SFDX Commands

I working on better query formatting and other util otions ;)

I hope you like the enhacements and sorry to impement it to late ;)
